name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy the app
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          php artisan deploy --api-key $MAPS_API_KEY
