name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Deploy the app
        env:
          MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
        run: |
          echo "MAPS_API_KEY=${MAPS_API_KEY}" >> $GITHUB_ENV
